name: Run Script with GitHub Token

on:
  workflow_dispatch:  # Allows manual trigger from the Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      GH_API_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_USERNAME: ${{ github.repository_owner }}
      GH_REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python ./scripts/issue.py
